// ===== Pathbound (Idle rework) — game data & config =====
'use strict';

const STATS = ['str', 'end', 'dex', 'agi', 'int', 'wis', 'fai', 'pie', 'sol', 'per'];

const STAT_INFO = {
  str: { name: 'Strength',     abbr: 'STR', color: '#e8645a' },
  end: { name: 'Endurance',    abbr: 'END', color: '#e8945a' },
  dex: { name: 'Dexterity',    abbr: 'DEX', color: '#9de85a' },
  agi: { name: 'Agility',      abbr: 'AGI', color: '#5ae87a' },
  int: { name: 'Intelligence', abbr: 'INT', color: '#5aa9e8' },
  wis: { name: 'Wisdom',       abbr: 'WIS', color: '#5ae8c0' },
  fai: { name: 'Faith',        abbr: 'FAI', color: '#e8d65a' },
  pie: { name: 'Piety',        abbr: 'PIE', color: '#e8b85a' },
  sol: { name: 'Soul',         abbr: 'SOL', color: '#b07ae8' },
  per: { name: 'Perseverance', abbr: 'PER', color: '#e8c468' },
};

const CFG = {
  tickMs: 100,
  startStat: 5,
  slotCount: 8,
  cdSkill: 2,
  cdSpell: 3,
  dazedSlow: 0.9,
  dazedSecs: 0.25,
  winsToAdvance: 10,
  levelCap: 1000,
  classlessUnlock: 30,
  upgradeFlatStep: 1,
  upgradeMult: 1.1,
  upgradeUnlock: 30,
  prestigeLevel: 100,
  prestigeDivisor: 9,
  prestigeSpeedPerClass: 0.5,
  masteryLevel: 300,        // class level required to Master it
  masteryXpFlat: 100,       // +100 base victory XP per Mastery...
  masteryXpPct: 1,          // ...then +100% per Mastery
  masteryMultCut: 0.01,     // each Mastery cuts higher-tier compound multipliers by this
  dropChance: 0.10,
  runeChance: 0.01,
  tomeChance: 0.001,
  invSize: 100,
  prefixChances: [1, 0.5, 0.1, 0.01, 0.001],
  multChances: [[2, 0.10], [3, 0.01], [4, 0.001]],
  maxItemUpgrades: 10,
  maxRerolls: 6,
  rerollCosts: [250, 250, 500, 500, 1000, 1000], // cost of reroll n+1
  bsCosts: { upgrade: 100, extract: 500, augment: 1500 },
  tipLinger: 3,          // seconds a tooltip stays after release
  maxAllies: 4,          // per side
  dmgScale: 1,
};

const EQUIP_SLOTS = {
  head: 'Helm', chest: 'Cuirass', legs: 'Leggings',
  feet: 'Greaves', hands: 'Gauntlets', shoulders: 'Pauldron',
};
const GEAR_STATS = ['str', 'end', 'dex', 'agi', 'int', 'wis', 'fai', 'pie'];

// ---- status keywords ----
// kind: 'charge' (consumed by damaging abilities), 'stack' (per-stack timers,
// values snapshot the inflictor's stats), 'dur' (single timer), 'instant'.
const STATUSES = {
  guilt:       { name: 'Guilt',       kind: 'charge', bad: true, desc: 'Your next X damaging abilities deal half damage' },
  confusion:   { name: 'Confusion',   kind: 'charge', bad: true, desc: 'Your next X damaging abilities have a 50% chance of damaging yourself instead' },
  empower:     { name: 'Empowerment', kind: 'charge', desc: 'Your next X damaging abilities also deal additional damage equal to your Piety' },
  plummet:     { name: 'Plummet',     kind: 'charge', bad: true, desc: 'Receive 50% more damage on the next X damaging hits' },
  blind:       { name: 'Blind',       kind: 'dur', bad: true, desc: 'Your abilities have 30% reduced chance to hit' },
  protection:  { name: 'Protection',  kind: 'dur', desc: 'Damage received reduced 25%' },
  interrupted: { name: 'Interrupted', kind: 'dur', bad: true, desc: 'Ability Speed stops' },
  intimidated: { name: 'Intimidated', kind: 'dur', bad: true, desc: 'Ability Speed −25%' },
  terror:      { name: 'Terror',      kind: 'dur', bad: true, desc: 'Ability Speed −50%' },
  enlarged:    { name: 'Enlarged',    kind: 'dur', desc: '+30% Endurance and Strength' },
  burdened:    { name: 'Burdened',    kind: 'dur', bad: true, desc: '−20% Strength, Agility and Dexterity' },
  unburdened:  { name: 'Unburdened',  kind: 'dur', desc: '+20% Strength, Agility and Dexterity' },
  shrink:      { name: 'Shrink',      kind: 'dur', desc: '20% chance to dodge damaging abilities' },
  agile:       { name: 'Agile',       kind: 'dur', desc: '+30% Attack Speed' },
  regen:       { name: 'Regen',       kind: 'dur', desc: 'Regenerate 5% max health per second' },
  taunt:       { name: 'Taunt',       kind: 'dur', bad: true, desc: 'A random ability gains +50% Ability Speed; the rest get −50%' },
  flight:      { name: 'Flight',      kind: 'dur', desc: '+50% Ability Speed. Taking 20% max health in damage ends Flight and inflicts Plummet 3' },
  stealth:     { name: 'Stealth',     kind: 'dur', desc: 'Damaging abilities cannot hit you. Ends when you deal damage' },
  dazed:       { name: 'Dazed',       kind: 'dur', bad: true, desc: 'Just hit: Ability Speed −10%' },
  cdfast:      { name: 'Momentum',    kind: 'dur', desc: 'Cooldowns 20% faster' },
  cdslow:      { name: 'Sluggish',    kind: 'dur', bad: true, desc: 'Cooldowns 20% slower' },
  latch:       { name: 'Latched',     kind: 'dur', bad: true, desc: 'Whenever you take damage, also receive Bleed 5' },
  unwavered:   { name: 'Unwavered',   kind: 'dur', desc: 'Flat damage reduction' },
  repent:      { name: 'Repentance',  kind: 'dur', desc: 'When damaged, reflect 50% of the damage back' },
  bleed:       { name: 'Bleed',       kind: 'stack', bad: true, desc: 'Take 3 + 0.2×STR damage/s per stack. Activating an ability deals 6 + 0.4×STR per stack, then removes the stack closest to expiring' },
  frost:       { name: 'Frost',       kind: 'stack', bad: true, desc: 'Ability Speed −10% per stack · hits deal 1 + 0.1×WIS extra per stack. At 10+ stacks: all are removed, dealing 3 + 0.3×WIS each, and you are Interrupted 2s' },
  poison:      { name: 'Poison',      kind: 'stack', bad: true, desc: 'Health regen stops · lose 1% max health/s, plus 2 + 0.2×DEX damage/s per stack' },
  mindrot:     { name: 'Mind Rot',    kind: 'stack', bad: true, desc: 'Take 3 + 0.3×INT damage/s and lose that much mana/s per stack. At 0 mana: stacks purge and you lose half your current health' },
  siphon:      { name: 'Siphon',      kind: 'stack', bad: true, desc: 'Lose 3% max health/s per stack; the inflictor heals the amount drained' },
  bruised:     { name: 'Bruised',     kind: 'stack', bad: true, desc: 'Skill damage received +50% per stack' },
  hemorrhage:  { name: 'Hemorrhage',  kind: 'stack', bad: true, desc: 'Take 5 + 0.4×STR damage/s per stack · healing received is halved' },
  fracture:    { name: 'Fracture',    kind: 'dur', bad: true, desc: 'Whenever you receive skill damage, gain a stack of Bruised 5' },
  enchant:     { name: 'Enchant',     kind: 'stack', desc: 'Your damaging hits also inflict the enchanted condition' },
  nausea:      { name: 'Nausea',      kind: 'instant', bad: true, desc: 'A random ready ability immediately goes on cooldown; its bar restarts' },
  concuss:     { name: 'Concuss',     kind: 'instant', bad: true, desc: 'A random ability\'s bar freezes for the duration' },
  purity:      { name: 'Purity',      kind: 'charge', desc: 'The next X debuffs you would receive are negated' },
};

// ability-type keywords (Bestiary)
const TYPE_KEYWORDS = {
  Skill: 'Costs stamina · fills at Attack Speed (1+AGI/100) · 2s cooldown',
  Spell: 'Costs mana or resonance · fills at Cast Speed (1+WIS/100) · 3s cooldown',
  Concept: 'A passive that occupies an ability slot. Some are negative',
  Ammo: 'Limited uses; when empty, reloads at 5× cooldown',
  Charge: 'No cooldown while charges remain; recharges at +50% cooldown per charge after the last',
  Burst: 'Fires its effects an additional time per Burst; cooldown ×(1+Burst)',
  Sustain: 'Effect persists and the cooldown waits. Taking enough damage ends the Sustain and starts the cooldown',
  Rally: 'Summons an ally who fights beside you',
  Initiate: 'Activates automatically at the start of combat (Concepts: once only). Some have bonus effects when initiating',
  Overcap: 'Shield may exceed its maximum; the excess decays 1% per second',
};

// ---- abilities ----
// flags: concept, negative, ammo:n, charge, burst:n, sustain:{...}, rally,
//        initiate, startCd, followUp, speedLink:{id,mult}, special, draft,
//        noLearn, sameAs (renamed/upgraded copy for tome de-dupe)
// ops: dmg(base,mult,stat[,stat2],kind,pierce,leech,recoil) · heal · shield(overcap)
//      st(key,dur,count,stacks,to) · buff/weaken/dot (legacy)
const ABILITIES = {
  // ===== Classless =====
  'basic-strike':   { name: 'Basic Strike', tag: 'str', cost: { stam: 3 },
    full: [{ t: 'dmg', base: 1, mult: 1, stat: 'str', kind: 'phys' }] },
  'follow-up-slash':{ name: 'Follow-up Slash', tag: 'dex', cost: { stam: 5 }, followUp: true,
    followDmg: { base: 3, mult: 0.1, stat: 'dex' },
    desc: 'Whenever another skill deals damage, this skill gains +25% Attack Speed and +3 + 0.1 × Dexterity damage (stacking). Resets when this deals damage.',
    full: [{ t: 'dmg', base: 2, mult: 1.3, stat: 'dex', kind: 'phys' }] },
  'magic-pebble':   { name: 'Magic Pebble', tag: 'int', cost: { mana: 3 },
    full: [{ t: 'dmg', base: 1, mult: 1, stat: 'int', kind: 'mag' }] },
  'protection':     { name: 'Protection', tag: 'fai', cost: { reson: 10 },
    full: [{ t: 'st', key: 'protection', dur: 5, to: 'self' }] },
  'body-bash':      { name: 'Body Bash', tag: 'end', cost: { stam: 12 }, doubleIfProtected: true,
    desc: 'Deals double damage while your Protection buff is active.',
    full: [{ t: 'dmg', base: 0, pctMaxHp: 0.10, mult: 2, stat: 'end', kind: 'phys' }] },
  'leaping-strike': { name: 'Leaping Strike', tag: 'agi', cost: { stam: 8 },
    full: [{ t: 'st', key: 'agile', dur: 2, to: 'self' },
           { t: 'dmg', base: 5, mult: 1.5, stat: 'agi', kind: 'phys' }] },
  'obscure-vision': { name: 'Obscure Vision', tag: 'wis', cost: { mana: 12 },
    full: [{ t: 'st', key: 'blind', dur: 6, to: 'foe' },
           { t: 'st', key: 'stealth', dur: 10, to: 'self' }] },
  'empowerment':    { name: 'Empowerment', tag: 'pie', cost: { reson: 10 },
    full: [{ t: 'st', key: 'empower', count: 2, to: 'self' }] },
  'determination':  { name: 'Determination', tag: 'sol', cost: {}, concept: true,
    desc: 'Increase Soul and Perseverance by 0.2% × highest Classless level reached.' },

  // ===== Tier 0.5 =====
  'preemptive-strike': { name: 'Preemptive Strike', tag: 'str', cost: { stam: 4 }, initiate: true,
    desc: 'Initiate: fires at combat start, inflicting Interrupted 1 and dealing double damage.',
    initOps: [{ t: 'st', key: 'interrupted', dur: 1, to: 'foe' }],
    initDmgMult: 2,
    full: [{ t: 'dmg', base: 5, mult: 0.7, stat: 'str', kind: 'phys' }] },
  'remove-weights': { name: 'Remove Training Weights', tag: 'end', cost: { stam: 12 },
    full: [{ t: 'st', key: 'unburdened', dur: 5, to: 'self' }] },
  'disciplined':    { name: 'Disciplined', tag: 'end', cost: {}, concept: true,
    desc: 'Receiving damage does not slow your Ability Speed.' },
  'quick-flurry':   { name: 'Quick Flurry', tag: 'dex', cost: { stam: 3 }, ammo: 4,
    full: [{ t: 'dmg', base: 3, mult: 1, stat: 'dex', kind: 'phys' }] },
  'momentum-shift': { name: 'Momentum Shift', tag: 'agi', cost: { stam: 8 },
    full: [{ t: 'st', key: 'cdfast', dur: 6, to: 'self' }, { t: 'st', key: 'cdslow', dur: 6, to: 'foe' }] },
  'tireless':       { name: 'Tireless', tag: 'agi', cost: {}, concept: true,
    desc: 'Your cooldowns are reduced by 0.5 seconds.' },
  'fire-bolt':      { name: 'Frost Bolt', tag: 'int', cost: { mana: 6 },
    full: [{ t: 'st', key: 'frost', dur: 5, to: 'foe' },
           { t: 'dmg', base: 7, mult: 1.5, stat: 'int', kind: 'mag' }] },
  'ward':           { name: 'Ward', tag: 'wis', cost: { mana: 8 },
    desc: 'Can Overcap: shield may exceed its maximum; excess decays 1%/s.',
    full: [{ t: 'shield', base: 5, mult: 0.7, stat: 'wis', overcap: true }] },
  'creeping-frost': { name: 'Creeping Frost', tag: 'int', cost: {}, concept: true,
    desc: 'Whenever you inflict Frost, all future Frost you inflict lasts +1s longer (until combat ends).' },
  'read-scripture': { name: 'Read Scripture', tag: 'fai', cost: { reson: 10 },
    full: [{ t: 'st', key: 'regen', dur: 3, to: 'self' }] },
  'frost-scroll':   { name: 'Create Frost Scroll', tag: 'pie', cost: { reson: 7 },
    full: [{ t: 'st', key: 'frost', dur: 4, to: 'foe' },
           { t: 'dmg', base: 3, mult: 1.1, stat: 'pie', kind: 'mag' }] },
  'watched-over':   { name: 'Watched Over', tag: 'fai', cost: {}, concept: true,
    desc: 'Twice your Faith is added to your maximum health.' },

  // ===== Tier 1 class tracks =====
  'crushing-blow':  { name: 'Crushing Blow', tag: 'end', cost: { stam: 10 },
    full: [{ t: 'st', key: 'bruised', dur: 3, to: 'foe' },
           { t: 'dmg', base: 15, mult: 2, stat: 'end', kind: 'phys' }] },
  'extremity-strike': { name: 'Extremity Strike', tag: 'str', cost: { stam: 8 },
    full: [{ t: 'st', key: 'fracture', dur: 2, to: 'foe' },
           { t: 'dmg', base: 10, mult: 1.5, stat: 'str', kind: 'phys' }] },
  'guard-breaker':  { name: 'Guard Breaker', tag: 'str', cost: {}, concept: true,
    desc: 'Whenever the enemy\'s mana shield is fully depleted, inflict Interrupted 2 and Bleed 3.' },
  'smoke-bomb':     { name: 'Smoke Bomb', tag: 'agi', cost: { stam: 6 },
    full: [{ t: 'st', key: 'blind', dur: 3, to: 'foe' }, { t: 'st', key: 'interrupted', dur: 1, to: 'foe' }] },
  'poison-enchant': { name: 'Poison Enchant', tag: 'dex', cost: { stam: 12 },
    full: [{ t: 'st', key: 'enchant', dur: 10, to: 'self', enchKey: 'poison', enchDur: 3 }] },
  'deadly-ambush':  { name: 'Deadly Ambush', tag: 'dex', tag2: 'agi', cost: {}, concept: true, initiate: true,
    desc: 'Initiate: at the start of combat, inflict Poison 3 and deal 15 + 2 × (DEX + AGI) damage.',
    initOps: [{ t: 'st', key: 'poison', dur: 3, to: 'foe' },
              { t: 'dmg', base: 15, mult: 2, stat: 'dex', stat2: 'agi', kind: 'phys' }] },
  'bounty-hunter':  { name: 'Bounty Hunter', tag: 'dex', cost: { stam: 12 }, special: 'bounty',
    desc: 'If this deals the finishing blow, gain extra gold equal to the overkill.',
    full: [{ t: 'dmg', base: 15, mult: 1.8, stat: 'dex', kind: 'phys' }] },
  'trick-blade':    { name: 'Trick Blade', tag: 'dex', cost: { stam: 8 }, ammo: 1,
    full: [{ t: 'st', key: 'bleed', dur: 3, to: 'foe' },
           { t: 'dmg', base: 30, mult: 2.5, stat: 'dex', kind: 'phys' }] },
  'battle-conscious': { name: 'Battle Conscious', tag: 'end', cost: {}, concept: true,
    desc: 'Attack Speed cannot drop below 100% unless Interrupted.' },
  'double-twin-fist': { name: 'Double Twin Fist', tag: 'str', cost: { stam: 9 }, charge: true, ammo: 2, burst: 1,
    full: [{ t: 'dmg', base: 12, mult: 1, stat: 'str', kind: 'phys' }] },
  'cleanse':        { name: 'Cleanse', tag: 'pie', cost: { reson: 5 },
    full: [{ t: 'st', key: 'purity', count: 1, to: 'self' },
           { t: 'st', key: 'regen', dur: 3, to: 'self' }] },
  'in-the-name-of': { name: 'In The Name Of...', tag: 'pie', cost: {}, concept: true,
    desc: 'Gain 1 Empowerment every 2 seconds. Resonance does not regenerate.' },
  'magic-missile':  { name: 'Magic Missile', tag: 'int', cost: { mana: 5 }, charge: true, ammo: 3,
    full: [{ t: 'dmg', base: 31, mult: 1.6, stat: 'int', kind: 'mag' }] },
  'arcane-blast':   { name: 'Arcane Blast', tag: 'int', tag2: 'wis', cost: { mana: 15 }, ammo: 1,
    full: [{ t: 'dmg', base: 80, mult: 2.5, stat: 'int', stat2: 'wis', kind: 'mag' }] },
  'arcane-crafted': { name: 'Arcane Crafted', tag: 'int', cost: {}, concept: true,
    desc: 'Spells that complete their full cast time deal 50% more damage.' },
  'unwavered-spell':{ name: 'Unwavered', tag: 'fai', cost: { reson: 20 },
    full: [{ t: 'st', key: 'unwavered', dur: 20, to: 'self', valBase: 2, valMult: 0.1, valStat: 'fai' }] },
  'repent-evil':    { name: 'Repent Evil', tag: 'fai', cost: { reson: 30 },
    full: [{ t: 'st', key: 'repent', dur: 12, to: 'self' }] },
  'holier-than-thou': { name: 'Holier Than Thou', tag: 'fai', cost: {}, concept: true,
    desc: 'While Resonance is full, deal damage/s equal to your Resonance regen. Casting a Faith spell multiplies Resonance regen by 1.5.' },

  // ===== Book 1 enemy abilities =====
  'stare-menacingly': { name: 'Stare Menacingly', tag: 'end', cost: { stam: 6 },
    full: [{ t: 'st', key: 'interrupted', dur: 1, to: 'foe' }] },
  'intimidating-demeanor': { name: 'Intimidating Demeanor', tag: 'end', cost: { stam: 10 },
    full: [{ t: 'st', key: 'intimidated', dur: 4, to: 'foe' }] },
  'being-bigger':   { name: 'Being Bigger', tag: 'end', cost: { stam: 8 },
    full: [{ t: 'st', key: 'enlarged', dur: 5, to: 'self' }] },
  'buckle':         { name: 'Buckle', tag: 'end', cost: {}, concept: true, negative: true, noLearn: true,
    desc: 'Damage received accumulates; at 20% of max health, lose 10% max health and take 5% max health extra damage. Healing does not undo it.' },
  'left-fist':      { name: 'Left Fist', tag: 'str', cost: { stam: 2 },
    full: [{ t: 'dmg', base: 5, mult: 1, stat: 'str', kind: 'phys' }] },
  'right-fist':     { name: 'Right Fist', tag: 'str', cost: { stam: 2 }, startCd: true,
    full: [{ t: 'dmg', base: 10, mult: 1, stat: 'str', kind: 'phys' }] },
  'weak-swing':     { name: 'Weak Swing', tag: 'str', cost: { stam: 3 },
    full: [{ t: 'dmg', base: 5, mult: 1.1, stat: 'str', kind: 'phys' }] },
  'drop-shield':    { name: 'Drop Shield', tag: 'end', cost: { stam: 4 },
    full: [{ t: 'st', key: 'guilt', count: 1, to: 'foe' }] },
  'cower':          { name: 'Cower', tag: 'dex', cost: { stam: 4 },
    full: [{ t: 'st', key: 'shrink', dur: 4, to: 'self' }] },
  'vengeful-strike':{ name: 'Vengeful Strike', tag: 'str', cost: { stam: 4 },
    full: [{ t: 'dmg', base: 5, mult: 1.3, stat: 'str', kind: 'phys' }] },
  'you-monster':    { name: 'You Monster!', tag: 'wis', cost: { mana: 5 },
    full: [{ t: 'st', key: 'guilt', count: 1, to: 'foe' }] },
  'skull-crack':    { name: 'Skull Crack', tag: 'str', cost: { stam: 12 },
    full: [{ t: 'st', key: 'concuss', dur: 3, to: 'foe' },
           { t: 'dmg', base: 20, mult: 1.5, stat: 'str', kind: 'phys' }] },
  'back-in-my-day': { name: 'Back in my Day..', tag: 'wis', cost: { mana: 8 },
    full: [{ t: 'st', key: 'intimidated', dur: 3, to: 'foe' }] },
  'where-am-i':     { name: 'Where am I??', tag: 'wis', cost: { mana: 10 },
    full: [{ t: 'st', key: 'confusion', count: 1, to: 'both' }] },
  'shuffle':        { name: 'Shuffle', tag: 'agi', cost: { stam: 6 },
    full: [{ t: 'st', key: 'agile', dur: 4, to: 'self' }] },
  'cane-swipe':     { name: 'Cane Swipes', tag: 'dex', cost: { stam: 3 }, ammo: 3, charge: true,
    full: [{ t: 'dmg', base: 4, mult: 1.1, stat: 'dex', kind: 'phys' }] },
  'twin-strike':    { name: 'Twin Strike', tag: 'dex', cost: { stam: 5 },
    full: [{ t: 'dmg', base: 3, mult: 1.1, stat: 'dex', kind: 'phys' },
           { t: 'dmg', base: 3, mult: 1.1, stat: 'dex', kind: 'phys' }] },
  'throwing-dagger':{ name: 'Throwing Dagger', tag: 'dex', cost: { stam: 3 }, ammo: 3,
    full: [{ t: 'dmg', base: 3, mult: 1.8, stat: 'dex', kind: 'phys' }] },
  'leg-sweep':      { name: 'Leg Sweep', tag: 'agi', cost: { stam: 6 },
    full: [{ t: 'st', key: 'interrupted', dur: 1, to: 'foe' },
           { t: 'dmg', base: 6, mult: 1.2, stat: 'agi', kind: 'phys' }] },
  'viper-strike':   { name: 'Viper Strike', tag: 'agi', cost: { stam: 2 },
    full: [{ t: 'dmg', base: 3, mult: 1.2, stat: 'agi', kind: 'phys' }] },
  'poison-dagger':  { name: 'Poison Dagger', tag: 'dex', cost: { stam: 5 },
    full: [{ t: 'st', key: 'poison', dur: 3, to: 'foe' },
           { t: 'dmg', base: 1, mult: 1, stat: 'dex', kind: 'phys' }] },
  'distract':       { name: 'Distract', tag: 'wis', cost: { mana: 4 },
    full: [{ t: 'st', key: 'interrupted', dur: 1, to: 'foe' }] },
  'whirlwind-slash':{ name: 'Whirlwind Slash', tag: 'str', cost: { stam: 2 }, ammo: 3, charge: true,
    full: [{ t: 'dmg', base: 5, mult: 1.2, stat: 'str', kind: 'phys' }] },
  'icicle-darts':   { name: 'Icicle Darts', tag: 'int', cost: { mana: 2 }, ammo: 5, charge: true,
    full: [{ t: 'dmg', base: 1, mult: 1.1, stat: 'int', kind: 'mag' }] },
  'counter-strike': { name: 'Counter Strike', tag: 'str', cost: { stam: 6 }, special: 'counter',
    desc: 'Next time you receive damage, deal 50% of it back plus 3 + 1.1 × Strength.',
    full: [] },
  'glacial-fist':   { name: 'Glacial Fist', tag: 'str', tag2: 'int', cost: { stam: 8 },
    full: [{ t: 'dmg', base: 12, mult: 1, stat: 'str', stat2: 'int', kind: 'phys' }] },
  'be-adorable':    { name: 'Be Adorable', tag: 'wis', cost: { mana: 3 },
    full: [{ t: 'st', key: 'guilt', count: 1, to: 'foe' }] },
  'knaw':           { name: 'Knaw', tag: 'str', cost: { stam: 2 },
    full: [{ t: 'st', key: 'bleed', dur: 2, to: 'foe' },
           { t: 'dmg', base: 3, mult: 1.1, stat: 'str', kind: 'phys' }] },
  'skittish':       { name: 'Skittish', tag: 'agi', cost: {}, concept: true,
    desc: 'Damage dealt and received is halved · chance to hit and be hit is halved.' },
  'flee':           { name: 'Attempt to Flee', tag: 'agi', cost: { stam: 30 }, special: 'flee', noLearn: true,
    desc: 'Combat ends. No victory, no drops, no XP.',
    full: [] },
  'jump-attack':    { name: 'Jump Attack', tag: 'agi', cost: { stam: 3 },
    full: [{ t: 'dmg', base: 5, mult: 1.1, stat: 'agi', kind: 'phys' }] },
  'vibrate':        { name: 'Vibrate', tag: 'end', cost: { stam: 8 },
    full: [{ t: 'st', key: 'regen', dur: 3, to: 'self' }] },
  'diseased':       { name: 'Diseased', tag: 'end', cost: {}, concept: true, negative: true, noLearn: true,
    desc: 'No natural health regen.' },
  'projectile-bile':{ name: 'Projectile Bile', tag: 'end', cost: { stam: 7 },
    full: [{ t: 'st', key: 'poison', dur: 7, to: 'foe' },
           { t: 'dmg', base: 1, mult: 1.1, stat: 'end', kind: 'phys' }] },
  'gnash-teeth':    { name: 'Gnash Teeth', tag: 'end', cost: { stam: 4 },
    full: [{ t: 'st', key: 'intimidated', dur: 3, to: 'foe' }] },
  'putrid-smell':   { name: 'Putrid Smell', tag: 'end', cost: { stam: 6 },
    full: [{ t: 'st', key: 'nausea', dur: 4, to: 'foe' }] },
  'rebound':        { name: 'Rebound', tag: 'agi', cost: {}, concept: true,
    desc: 'Agility skills have no cooldown.' },
  'gunk-shot':      { name: 'Gunk Shot', tag: 'end', cost: { stam: 8 },
    full: [{ t: 'st', key: 'interrupted', dur: 2, to: 'foe' },
           { t: 'dmg', base: 1, mult: 1.7, stat: 'end', kind: 'phys' }] },
  'serpentine':     { name: 'Serpentine Maneuver', tag: 'agi', cost: { stam: 7 },
    full: [{ t: 'st', key: 'agile', dur: 3, to: 'self' }] },
  'war-cry-smol':   { name: 'War Cry (smol)', tag: 'end', cost: { stam: 10 },
    full: [{ t: 'st', key: 'intimidated', dur: 6, to: 'foe' }] },
  'headbutt':       { name: 'Headbutt', tag: 'dex', tag2: 'end', cost: { stam: 10 },
    full: [{ t: 'dmg', base: 5, mult: 1, stat: 'dex', stat2: 'end', kind: 'phys' }] },
  'fury':           { name: 'Fury', tag: 'str', cost: {}, concept: true,
    desc: 'Whenever you take damage, your Strength skills deal +1 damage this combat.' },
  'claw-swipes':    { name: 'Claw Swipes', tag: 'dex', cost: { stam: 3 }, ammo: 3, charge: true,
    full: [{ t: 'dmg', base: 5, mult: 1.3, stat: 'dex', kind: 'phys' }] },
  'rock-throw':     { name: 'Rock Throw', tag: 'str', cost: { stam: 3 },
    full: [{ t: 'dmg', base: 1, mult: 1.2, stat: 'str', kind: 'phys' }] },
  'knee-in-groin':  { name: 'Knee in Groin', tag: 'str', cost: { stam: 2 },
    full: [{ t: 'st', key: 'interrupted', dur: 2, to: 'foe' },
           { t: 'dmg', base: 10, mult: 1.3, stat: 'str', kind: 'phys' }] },
  'bonk-on-head':   { name: 'Bonk on Head', tag: 'str', cost: { stam: 2 }, startCd: true,
    full: [{ t: 'st', key: 'concuss', dur: 2, to: 'foe' },
           { t: 'dmg', base: 10, mult: 1.3, stat: 'str', kind: 'phys' }] },
  'wack':           { name: 'Wack', tag: 'str', cost: { stam: 5 }, speedLink: { id: 'thwack', mult: 2 },
    desc: 'Hastens Thwack: +100% Attack Speed until it deals damage.',
    full: [{ t: 'dmg', base: 5, mult: 1.5, stat: 'str', kind: 'phys' }] },
  'thwack':         { name: 'Thwack', tag: 'str', cost: { stam: 10 }, speedLink: { id: 'crack', mult: 2 },
    desc: 'Hastens Crack!: +100% Attack Speed until it deals damage.',
    full: [{ t: 'dmg', base: 10, mult: 2, stat: 'str', kind: 'phys' }] },
  'crack':          { name: 'Crack!', tag: 'str', cost: { stam: 20 },
    full: [{ t: 'st', key: 'bruised', dur: 8, to: 'foe' },
           { t: 'dmg', base: 20, mult: 2.5, stat: 'str', kind: 'phys' }] },
  'whats-uhh':      { name: 'What\'s uhh..', tag: 'wis', cost: { mana: 20 },
    full: [{ t: 'st', key: 'confusion', count: 5, to: 'self' }] },

  // ===== Book 2 Chapter 1 =====
  'halt':           { name: 'Halt!', tag: 'wis', cost: { mana: 5 },
    full: [{ t: 'st', key: 'interrupted', dur: 2, to: 'foe' }] },
  'present-papers': { name: 'Present Your Papers!', tag: 'wis', cost: { mana: 6 },
    full: [{ t: 'st', key: 'confusion', count: 3, to: 'foe' }] },
  'back-of-line':   { name: 'Back Of The Line!', tag: 'str', cost: { stam: 7 },
    full: [{ t: 'st', key: 'intimidated', dur: 2, to: 'foe' }, { t: 'st', key: 'concuss', dur: 1, to: 'foe' },
           { t: 'dmg', base: 10, mult: 2, stat: 'str', kind: 'phys' }] },
  'pay-the-fine':   { name: 'Pay The Fine!', tag: 'end', cost: { stam: 5 },
    full: [{ t: 'st', key: 'guilt', count: 2, to: 'foe' }, { t: 'st', key: 'bleed', dur: 5, stacks: 2, to: 'foe' }] },
  'disrespect-toll':{ name: 'Disrespect My Toll?!', tag: 'pie', cost: { reson: 6 },
    full: [{ t: 'st', key: 'empower', count: 2, to: 'self' }] },
  'deals-to-die-for': { name: 'These Deals Are To Die For!', tag: 'int', cost: { mana: 6 },
    full: [{ t: 'st', key: 'siphon', dur: 5, to: 'foe' }] },
  'special-recipe': { name: 'My Special Recipe, You Must Try!', tag: 'dex', cost: { stam: 5 },
    full: [{ t: 'st', key: 'poison', dur: 8, to: 'foe' }, { t: 'st', key: 'nausea', dur: 2, to: 'foe' },
           { t: 'dmg', base: 8, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'supposed-sharp': { name: 'It\'s Supposed To Be Sharp!', tag: 'end', cost: { stam: 7 },
    full: [{ t: 'st', key: 'bleed', dur: 6, to: 'foe' }] },
  'dont-be-picky':  { name: 'Don\'t Be So Picky!', tag: 'str', cost: { stam: 4 },
    full: [{ t: 'st', key: 'intimidated', dur: 4, to: 'foe' }, { t: 'st', key: 'guilt', count: 2, to: 'foe' }] },
  'one-for-two':    { name: 'We Have a 1 for 2 Deal Right Now!', tag: 'int', cost: { mana: 10 },
    full: [{ t: 'st', key: 'confusion', count: 4, to: 'foe' }, { t: 'st', key: 'mindrot', dur: 4, to: 'foe' }] },
  'hand-over-coin': { name: 'Hand Over The Coin, Bud!', tag: 'str', cost: { stam: 4 },
    full: [{ t: 'st', key: 'intimidated', dur: 5, to: 'foe' },
           { t: 'dmg', base: 12, mult: 1.7, stat: 'str', kind: 'phys' }] },
  'swiping-slash':  { name: 'Swiping Slash', tag: 'dex', cost: { stam: 3 }, ammo: 2, charge: true,
    full: [{ t: 'dmg', base: 12, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'guys-broke':     { name: 'Hey, This Guy\'s Broke!', tag: 'wis', cost: { mana: 8 },
    full: [{ t: 'st', key: 'taunt', dur: 5, to: 'foe' }] },
  'skidaddle':      { name: 'Skidaddle', tag: 'agi', cost: { stam: 30 }, special: 'flee', noLearn: true, sameAs: 'flee',
    desc: 'Combat ends. No victory, no drops, no XP.', full: [] },

  // ===== Book 2 Chapter 2 =====
  'viper-strike-u': { name: 'Viper Strike {U}', tag: 'agi', cost: { stam: 2 }, burst: 1, sameAs: 'viper-strike',
    full: [{ t: 'st', key: 'poison', dur: 2, to: 'foe' },
           { t: 'dmg', base: 5, mult: 1.3, stat: 'agi', kind: 'phys' }] },
  'poison-daggers-u': { name: 'Poison Daggers {U}', tag: 'dex', cost: { stam: 4 }, ammo: 3, sameAs: 'poison-dagger',
    full: [{ t: 'st', key: 'poison', dur: 3, to: 'foe' },
           { t: 'dmg', base: 5, mult: 1, stat: 'dex', kind: 'phys' }] },
  'bolas-toss':     { name: 'Bolas Toss', tag: 'dex', cost: { stam: 8 },
    full: [{ t: 'st', key: 'burdened', dur: 5, to: 'foe' },
           { t: 'dmg', base: 5, mult: 1.5, stat: 'agi', kind: 'phys' }] },
  'spear-throw':    { name: 'Spear Throw', tag: 'dex', cost: { stam: 8 },
    full: [{ t: 'st', key: 'bleed', dur: 4, to: 'foe' },
           { t: 'dmg', base: 8, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'deflecting-stance': { name: 'Deflecting Stance', tag: 'dex', cost: { stam: 4 },
    full: [{ t: 'st', key: 'protection', dur: 4, to: 'self' }, { t: 'st', key: 'shrink', dur: 4, to: 'self' }] },
  'arterial-strike':{ name: 'Arterial Strike', tag: 'agi', cost: { stam: 7 },
    full: [{ t: 'st', key: 'bleed', dur: 8, to: 'foe' },
           { t: 'dmg', base: 7, mult: 1.4, stat: 'agi', kind: 'phys' }] },
  'jab-flurry':     { name: 'Jab Flurry', tag: 'dex', cost: { stam: 9 }, burst: 3,
    full: [{ t: 'dmg', base: 8, mult: 1.1, stat: 'dex', kind: 'phys' }] },
  'sonic-assault':  { name: 'Sonic Assault', tag: 'agi', tag2: 'dex', cost: { stam: 12 }, special: 'sonic',
    desc: 'Your highest stamina-cost ability gains Burst +1 for the rest of combat.',
    full: [] },
  'whirlwind-slash-b2': { name: 'Whirlwind Slash', tag: 'str', cost: { stam: 2 }, ammo: 4, sameAs: 'whirlwind-slash',
    full: [{ t: 'dmg', base: 1, mult: 1.1, stat: 'str', kind: 'phys' }] },
  'icicle-darts-u': { name: 'Icicle Darts {U}', tag: 'int', cost: { mana: 3 }, ammo: 4, sameAs: 'icicle-darts',
    full: [{ t: 'st', key: 'frost', dur: 3, to: 'foe' },
           { t: 'dmg', base: 4, mult: 1.2, stat: 'int', kind: 'mag' }] },
  'glacial-fist-u': { name: 'Glacial Fist {U}', tag: 'str', tag2: 'int', cost: { stam: 7 }, sameAs: 'glacial-fist',
    full: [{ t: 'st', key: 'frost', dur: 10, to: 'foe' },
           { t: 'dmg', base: 13, mult: 1.2, stat: 'str', stat2: 'int', kind: 'phys' }] },
  'frost-enchant':  { name: 'Frost Enchant', tag: 'int', cost: { mana: 14 },
    full: [{ t: 'st', key: 'enchant', dur: 30, to: 'self', enchKey: 'frost', enchDur: 5 }] },

  // ===== Book 2 Chapter 3 =====
  'hum-in-unison':  { name: 'Hum in Unison', tag: 'end', cost: { stam: 8 }, sameAs: 'vibrate',
    full: [{ t: 'st', key: 'regen', dur: 6, to: 'self' }] },
  'multiply':       { name: 'Multiply', tag: 'wis', cost: { mana: 40 }, rally: true,
    desc: 'An ally of this combat joins the fight. Mana cost doubles for the rest of combat.',
    full: [] },
  'gunk-bombardment': { name: 'Gunk Bombardment', tag: 'end', cost: { stam: 9 },
    full: [{ t: 'st', key: 'interrupted', dur: 2, to: 'foe' },
           { t: 'dmg', base: 20, mult: 1.7, stat: 'end', kind: 'phys' }] },
  'roar':           { name: 'Roar', tag: 'end', cost: { stam: 8 },
    full: [{ t: 'st', key: 'burdened', dur: 5, to: 'foe' }, { t: 'st', key: 'intimidated', dur: 5, to: 'foe' },
           { t: 'st', key: 'empower', count: 1, to: 'self' }] },
  'full-bore':      { name: 'Full Bore', tag: 'str', cost: { stam: 10 },
    full: [{ t: 'st', key: 'bruised', dur: 8, to: 'foe' },
           { t: 'dmg', base: 20, mult: 3, stat: 'str', kind: 'phys', recoil: 0.5 }] },
  'after-image':    { name: 'After Image', tag: 'agi', cost: { stam: 9 },
    full: [{ t: 'st', key: 'agile', dur: 5, to: 'self' }, { t: 'st', key: 'shrink', dur: 5, to: 'self' }] },
  'carotid-crunch': { name: 'Carotid Crunch', tag: 'str', cost: { stam: 12 },
    full: [{ t: 'st', key: 'hemorrhage', dur: 5, to: 'foe' },
           { t: 'dmg', base: 18, mult: 2, stat: 'str', kind: 'phys' }] },
  'camouflage':     { name: 'Camouflage', tag: 'agi', cost: { stam: 8 },
    full: [{ t: 'st', key: 'stealth', dur: 10, to: 'self' }] },
  'mandible-crunch':{ name: 'Mandible Crunch', tag: 'str', cost: { stam: 12 },
    full: [{ t: 'st', key: 'fracture', dur: 5, to: 'foe' },
           { t: 'dmg', base: 10, mult: 2, stat: 'str', kind: 'phys' }] },
  'take-flight':    { name: 'Take Flight', tag: 'end', cost: { stam: 14 },
    full: [{ t: 'st', key: 'flight', dur: 8, to: 'self' }] },
  'flanking-strike':{ name: 'Flanking Strike', tag: 'agi', cost: { stam: 12 }, burst: 1,
    full: [{ t: 'dmg', base: 5, mult: 1.3, stat: 'agi', kind: 'phys' }] },
  'howl':           { name: 'Howl', tag: 'wis', cost: { mana: 40 }, rally: true, ammo: 2,
    desc: 'An ally of this combat joins the fight. Mana cost doubles for the rest of combat.',
    full: [] },
  'pounce':         { name: 'Pounce', tag: 'agi', cost: { stam: 3 }, sameAs: 'jump-attack',
    full: [{ t: 'dmg', base: 5, mult: 1.1, stat: 'agi', kind: 'phys' }] },
  'latching-bite':  { name: 'Latching Bite', tag: 'str', cost: { stam: 10 },
    full: [{ t: 'st', key: 'latch', dur: 10, to: 'foe' }] },

  // ===== Book 2 Chapter 4 =====
  'ambush':         { name: 'Ambush', tag: 'dex', cost: {}, concept: true, initiate: true,
    desc: 'Initiate: at the start of combat, deal 8 + 1.5 × Dexterity damage and inflict Bleed 3.',
    initOps: [{ t: 'st', key: 'bleed', dur: 3, to: 'foe' },
              { t: 'dmg', base: 8, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'rope-snag':      { name: 'Rope Snag Trap', tag: 'dex', cost: { stam: 6 },
    full: [{ t: 'st', key: 'burdened', dur: 5, to: 'foe' }, { t: 'st', key: 'confusion', count: 1, to: 'foe' }] },
  'sedation-dart':  { name: 'Sedation Dart', tag: 'dex', cost: { stam: 7 }, ammo: 2,
    full: [{ t: 'st', key: 'nausea', dur: 2, to: 'foe' }, { t: 'st', key: 'poison', dur: 12, to: 'foe' },
           { t: 'dmg', base: 1, mult: 1.1, stat: 'dex', kind: 'phys' }] },
  'bone-knife':     { name: 'Bone Knife Swipe', tag: 'dex', cost: { stam: 8 },
    full: [{ t: 'st', key: 'bleed', dur: 8, to: 'foe' },
           { t: 'dmg', base: 20, mult: 2, stat: 'dex', kind: 'phys' }] },
  'leg-shot':       { name: 'Leg Shot', tag: 'dex', cost: { stam: 5 }, ammo: 3,
    full: [{ t: 'dmg', base: 5, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'scatter-shot':   { name: 'Scatter Shot', tag: 'dex', cost: { stam: 12 }, burst: 2,
    full: [{ t: 'dmg', base: 5, mult: 1.5, stat: 'dex', kind: 'phys' }] },
  'between-eyes':   { name: 'Right Between the Eyes', tag: 'dex', cost: { stam: 20 }, ammo: 1,
    full: [{ t: 'st', key: 'concuss', dur: 5, to: 'foe' },
           { t: 'dmg', base: 20, mult: 2.5, stat: 'dex', kind: 'phys' }] },
  'shield-bash':    { name: 'Shield Bash', tag: 'end', cost: { stam: 4 },
    full: [{ t: 'st', key: 'concuss', dur: 2, to: 'foe' },
           { t: 'dmg', base: 4, mult: 1.2, stat: 'end', kind: 'phys' }] },
  'fortified':      { name: 'Fortified', tag: 'end', cost: { stam: 7 },
    full: [{ t: 'st', key: 'protection', dur: 5, to: 'self' }, { t: 'st', key: 'empower', count: 1, to: 'self' }] },
  'simultaneous-slash': { name: 'Simultaneous Slash', tag: 'dex', cost: { stam: 8 }, burst: 1,
    full: [{ t: 'dmg', base: 10, mult: 1.6, stat: 'dex', kind: 'phys' }] },
  'panic':          { name: 'Panic', tag: 'wis', cost: {}, concept: true, negative: true, noLearn: true,
    desc: 'Once at or below 50% health: gain Agile and Confusion for the rest of combat.' },
  'swing-wildly':   { name: 'Swing Wildly', tag: 'str', cost: { stam: 6 }, ammo: 4, charge: true,
    full: [{ t: 'dmg', base: 10, mult: 1.8, stat: 'str', kind: 'phys' }] },
  'war-cry-hob':    { name: 'War Cry', tag: 'end', cost: { stam: 10 },
    full: [{ t: 'st', key: 'intimidated', dur: 6, to: 'foe' }, { t: 'st', key: 'interrupted', dur: 1, to: 'foe' },
           { t: 'st', key: 'enlarged', dur: 5, to: 'self' }] },
  'berserk':        { name: 'Berserk', tag: 'str', cost: {}, concept: true,
    desc: 'Deal 40% more damage · receive 20% more damage.' },
  'knee-in-groin-u':{ name: 'Knee in Groin {U}', tag: 'str', cost: { stam: 2 }, sameAs: 'knee-in-groin',
    full: [{ t: 'st', key: 'interrupted', dur: 2, to: 'foe' },
           { t: 'dmg', base: 12, mult: 1.5, stat: 'str', kind: 'phys' }] },
  'bonk-on-head-u': { name: 'Bonk on Head {U}', tag: 'str', cost: { stam: 2 }, startCd: true, sameAs: 'bonk-on-head',
    full: [{ t: 'st', key: 'concuss', dur: 2, to: 'foe' },
           { t: 'dmg', base: 12, mult: 1.5, stat: 'str', kind: 'phys' }] },
  'wack-u':         { name: 'Wack {U}', tag: 'str', cost: { stam: 5 }, speedLink: { id: 'thwack-u', mult: 2.5 }, sameAs: 'wack',
    desc: 'Hastens Thwack: +150% Attack Speed until it deals damage.',
    full: [{ t: 'dmg', base: 6, mult: 1.6, stat: 'str', kind: 'phys' }] },
  'thwack-u':       { name: 'Thwack {U}', tag: 'str', cost: { stam: 10 }, speedLink: { id: 'crack-u', mult: 2.5 }, sameAs: 'thwack',
    desc: 'Hastens Crack!: +150% Attack Speed until it deals damage.',
    full: [{ t: 'dmg', base: 11, mult: 2.1, stat: 'str', kind: 'phys' }] },
  'crack-u':        { name: 'Crack! {U}', tag: 'str', cost: { stam: 20 }, sameAs: 'crack',
    full: [{ t: 'st', key: 'bruised', dur: 10, to: 'foe' },
           { t: 'dmg', base: 40, mult: 2.6, stat: 'str', kind: 'phys' }] },
  'whats-that':     { name: 'What\'s That Over There!', tag: 'wis', cost: { mana: 5 },
    full: [{ t: 'st', key: 'interrupted', dur: 1, to: 'foe' }, { t: 'st', key: 'empower', count: 1, to: 'self' }] },

  // ===== Book 2 Chapter 5 =====
  'yelp':           { name: 'Yelp', tag: 'wis', cost: { mana: 5 },
    full: [{ t: 'st', key: 'guilt', count: 1, to: 'foe' }, { t: 'st', key: 'shrink', dur: 3, to: 'self' }] },
  'bite':           { name: 'Bite', tag: 'str', cost: { stam: 3 },
    full: [{ t: 'st', key: 'bleed', dur: 2, to: 'foe' },
           { t: 'dmg', base: 5, mult: 1.4, stat: 'str', kind: 'phys' }] },
  'nothingness':    { name: 'Nothingness', tag: 'sol', cost: {}, concept: true, negative: true, noLearn: true,
    desc: 'There is no fight here. You cannot perform any abilities.' },
  'too-quiet':      { name: 'It\'s too quiet...', tag: 'sol', cost: { stam: 10 }, noLearn: true, full: [] },
  'something-wrong':{ name: 'Something is wrong...', tag: 'sol', cost: { stam: 15 }, noLearn: true, full: [] },
  'neck-hairs':     { name: 'The hairs on your neck stand up', tag: 'sol', cost: { stam: 20 }, noLearn: true, full: [] },
  'not-supposed':   { name: 'YOU ARE NOT SUPPOSED TO BE HERE', tag: 'sol', cost: { stam: 30 }, special: 'endwin', noLearn: true,
    desc: 'Combat ends in 3 seconds. No rewards, but the victory counts.', full: [] },
  'have-to-run':    { name: 'You Have To Run!', tag: 'sol', cost: { stam: 15 }, noLearn: true, full: [] },
  'not-normal':     { name: 'That Thing Is Not Normal!', tag: 'sol', cost: { stam: 30 }, noLearn: true, full: [] },
  'slow-it-down':   { name: 'He Said He Would Slow It Down...', tag: 'sol', cost: { stam: 45 }, noLearn: true, full: [] },
  'just-leave-him': { name: 'But Can I Just Leave Him?', tag: 'sol', cost: { stam: 60 }, special: 'endwin', noLearn: true,
    desc: 'Combat ends in 3 seconds. No rewards, but the victory counts.', full: [] },

  // ===== Book 2 boss =====
  'ferocious-howl': { name: 'Ferocious Howl', tag: 'wis', cost: { mana: 8 },
    full: [{ t: 'st', key: 'terror', dur: 3, to: 'foe' }, { t: 'st', key: 'interrupted', dur: 1, to: 'foe' }] },
  'hatred-brews':   { name: 'Hatred Brews', tag: 'sol', cost: { mana: 10 }, special: 'hatred',
    desc: 'Increase all core stats by 10 for the combat. Stackable.',
    full: [] },
  'coagulated-claws': { name: 'Coagulated Claws', tag: 'dex', cost: { stam: 7 }, ammo: 2, charge: true,
    full: [{ t: 'st', key: 'bleed', dur: 5, to: 'foe' }, { t: 'st', key: 'poison', dur: 5, to: 'foe' },
           { t: 'dmg', base: 15, mult: 1.2, stat: 'dex', kind: 'phys' }] },
  'relentless-assault': { name: 'Relentless Assault', tag: 'str', cost: { stam: 9 }, burst: 2,
    full: [{ t: 'st', key: 'bleed', dur: 7, to: 'foe' }, { t: 'st', key: 'poison', dur: 7, to: 'foe' },
           { t: 'dmg', base: 20, mult: 1.3, stat: 'str', kind: 'phys' }] },
  'decisive-lunge': { name: 'Decisive Lunge', tag: 'agi', cost: { stam: 7 },
    full: [{ t: 'st', key: 'agile', dur: 3, to: 'self' },
           { t: 'dmg', base: 12, mult: 1.9, stat: 'agi', kind: 'phys' }] },
  'feast':          { name: 'Feast', tag: 'end', cost: { stam: 15 }, sustain: { thresholdPct: 0.10 },
    desc: 'Sustain: gain Regen while sustaining. Taking 10% max health in damage ends the Sustain.',
    full: [] },

  // ===== legacy draft pool (tier 1.5 drafts; can also include tome abilities) =====
  'slash':        { name: 'Slash', tag: 'str', cost: { stam: 5 }, draft: true,
    full: [{ t: 'dmg', base: 6, mult: 1.4, stat: 'str', kind: 'phys' }] },
  'heavy-blow':   { name: 'Heavy Blow', tag: 'str', cost: { stam: 9 }, draft: true,
    full: [{ t: 'dmg', base: 12, mult: 2.0, stat: 'str', kind: 'phys' }] },
  'shield-wall':  { name: 'Shield Wall', tag: 'end', cost: { stam: 6 }, draft: true,
    full: [{ t: 'shield', base: 8, mult: 2.0, stat: 'end' }] },
  'pierce':       { name: 'Pierce', tag: 'dex', cost: { stam: 5 }, draft: true,
    full: [{ t: 'dmg', base: 5, mult: 1.3, stat: 'dex', kind: 'phys', pierce: true }] },
  'swift-strike': { name: 'Swift Strike', tag: 'agi', cost: { stam: 4 }, draft: true,
    full: [{ t: 'dmg', base: 4, mult: 1.2, stat: 'agi', kind: 'phys' }] },
  'fireball':     { name: 'Fireball', tag: 'int', cost: { mana: 5 }, draft: true,
    full: [{ t: 'dmg', base: 8, mult: 1.8, stat: 'int', kind: 'mag' }] },
  'mend':         { name: 'Mend', tag: 'wis', cost: { mana: 5 }, draft: true,
    full: [{ t: 'heal', base: 8, mult: 2.0, stat: 'wis' }] },
  'smite':        { name: 'Smite', tag: 'fai', cost: { reson: 4 }, draft: true,
    full: [{ t: 'dmg', base: 6, mult: 1.5, stat: 'fai', kind: 'mag' }] },
  'blessing':     { name: 'Blessing', tag: 'fai', cost: { reson: 5 }, draft: true,
    full: [{ t: 'heal', base: 5, mult: 1.2, stat: 'fai' }] },
  'sanctify':     { name: 'Sanctify', tag: 'pie', cost: { reson: 5 }, draft: true,
    full: [{ t: 'shield', base: 6, mult: 1.5, stat: 'pie' }] },
  'soul-leech':   { name: 'Soul Leech', tag: 'sol', cost: { mana: 5 }, draft: true,
    full: [{ t: 'dmg', base: 5, mult: 1.2, stat: 'sol', kind: 'mag', leech: 0.5 }] },
  'spirit-burst': { name: 'Spirit Burst', tag: 'sol', cost: { mana: 6 }, draft: true,
    full: [{ t: 'dmg', base: 9, mult: 1.6, stat: 'sol', kind: 'mag' }] },
};
const SKILL_OR_BASIC = (id) => ABILITIES[id];
const SKILLS = ABILITIES;

// reverse-combat thematic names by stat tag
const REVERSE_NAMES = {
  str: 'Apply Pressure', end: 'Tear Fabric To Slow Bleed', dex: 'Give Chewing Herb',
  agi: 'Apply a Salve', int: 'Elevate The Wound', wis: 'Inspect Severity',
  pie: 'Healing Words', fai: 'Offer Prayer', sol: 'It Is Not Time Yet',
};

// ---- class tree ----
const CLASSES = {
  classless: {
    name: 'Classless', tier: 0, core: [], parents: [], unlock: [],
    baseXp: 10, flatStep: 5, xpMult: 1.025,
    unlocks: {
      1: ['basic-strike', 'follow-up-slash', 'magic-pebble', 'protection'],
      10: ['body-bash', 'leaping-strike', 'obscure-vision', 'empowerment'],
      100: ['determination'],
    },
    gains: [
      { everyN: 5, add: { str: 1, end: 1, dex: 1, agi: 1 } },
      { everyN: 6, add: { int: 1, wis: 1 } },
      { everyN: 7, add: { fai: 1, pie: 1 } },
      { everyN: 8, add: { sol: 1 } },
    ],
  },
  'squire-trainee': {
    name: 'Squire Trainee', tier: 0.5, core: ['str', 'end'],
    parents: ['classless'], unlock: [{ class: 'classless', level: 30 }],
    baseXp: 500, xpMult: 1.05,
    unlocks: { 1: ['preemptive-strike'], 10: ['remove-weights'], 100: ['disciplined'] },
    gains: [
      { everyN: 5, add: { str: 2, end: 2 } },
      { everyN: 6, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 7, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 8, add: { sol: 1 } },
    ],
  },
  'scouts-runner': {
    name: "Scout's Runner", tier: 0.5, core: ['dex', 'agi'],
    parents: ['classless'], unlock: [{ class: 'classless', level: 30 }],
    baseXp: 500, xpMult: 1.05,
    unlocks: { 1: ['quick-flurry'], 10: ['momentum-shift'], 100: ['tireless'] },
    gains: [
      { everyN: 5, add: { dex: 2, agi: 2 } },
      { everyN: 6, add: { str: 1, end: 1, dex: 1, agi: 1 } },
      { everyN: 7, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 8, add: { sol: 1 } },
    ],
  },
  'mages-apprentice': {
    name: "Mage's Apprentice", tier: 0.5, core: ['int', 'wis'],
    parents: ['classless'], unlock: [{ class: 'classless', level: 30 }],
    baseXp: 500, xpMult: 1.05,
    unlocks: { 1: ['fire-bolt'], 10: ['ward'], 100: ['creeping-frost'] },
    gains: [
      { everyN: 5, add: { int: 2, wis: 2 } },
      { everyN: 6, add: { int: 1, wis: 1, fai: 1, pie: 1 } },
      { everyN: 7, add: { str: 1, end: 1, dex: 1, agi: 1 } },
      { everyN: 8, add: { sol: 1 } },
    ],
  },
  'assistant-scribe': {
    name: 'Assistant Scribe', tier: 0.5, core: ['fai', 'pie'],
    parents: ['classless'], unlock: [{ class: 'classless', level: 30 }],
    baseXp: 500, xpMult: 1.05,
    unlocks: { 1: ['read-scripture'], 10: ['frost-scroll'], 100: ['watched-over'] },
    gains: [
      { everyN: 5, add: { fai: 2, pie: 2 } },
      { everyN: 6, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 7, add: { str: 1, end: 1, dex: 1, agi: 1 } },
      { everyN: 8, add: { sol: 1 } },
    ],
  },
  fighter: {
    name: 'Fighter', tier: 1, core: ['str', 'end'],
    parents: ['squire-trainee'], unlock: [{ class: 'squire-trainee', level: 40 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['crushing-blow'], 10: ['extremity-strike'], 100: ['guard-breaker'] },
    gains: [
      { everyN: 4, add: { str: 2, end: 2 } },
      { everyN: 5, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 6, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 7, add: { sol: 1, str: 1, end: 1 } },
    ],
  },
  rogue: {
    name: 'Rogue', tier: 1, core: ['dex', 'agi'],
    parents: ['scouts-runner'], unlock: [{ class: 'scouts-runner', level: 40 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['smoke-bomb'], 10: ['poison-enchant'], 100: ['deadly-ambush'] },
    gains: [
      { everyN: 4, add: { dex: 2, agi: 2 } },
      { everyN: 5, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 6, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 7, add: { sol: 1, dex: 1, agi: 1 } },
    ],
  },
  mercenary: {
    name: 'Mercenary', tier: 1, core: ['dex', 'end'],
    parents: ['squire-trainee', 'scouts-runner'],
    unlock: [{ class: 'squire-trainee', level: 25 }, { class: 'scouts-runner', level: 25 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['bounty-hunter'], 10: ['trick-blade'], 100: ['battle-conscious'] },
    gains: [
      { everyN: 4, add: { dex: 2, end: 2 } },
      { everyN: 5, add: { str: 1, end: 1, dex: 1, agi: 1 } },
      { everyN: 6, add: { int: 1, wis: 1, pie: 1, fai: 1 } },
      { everyN: 7, add: { sol: 1, dex: 1, end: 1 } },
    ],
  },
  monk: {
    name: 'Monk', tier: 1, core: ['pie', 'str'],
    parents: ['squire-trainee', 'assistant-scribe'],
    unlock: [{ class: 'squire-trainee', level: 25 }, { class: 'assistant-scribe', level: 25 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['double-twin-fist'], 10: ['cleanse'], 100: ['in-the-name-of'] },
    gains: [
      { everyN: 4, add: { pie: 2, str: 2 } },
      { everyN: 5, add: { fai: 1, pie: 1, str: 1, end: 1 } },
      { everyN: 6, add: { dex: 1, agi: 1, int: 1, wis: 1 } },
      { everyN: 7, add: { sol: 1, pie: 1, str: 1 } },
    ],
  },
  mage: {
    name: 'Mage', tier: 1, core: ['int', 'wis'],
    parents: ['mages-apprentice'], unlock: [{ class: 'mages-apprentice', level: 40 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['magic-missile'], 10: ['arcane-blast'], 100: ['arcane-crafted'] },
    gains: [
      { everyN: 4, add: { int: 2, wis: 2 } },
      { everyN: 5, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 6, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 7, add: { sol: 1, int: 1, wis: 1 } },
    ],
  },
  deacon: {
    name: 'Deacon', tier: 1, core: ['pie', 'fai'],
    parents: ['assistant-scribe'], unlock: [{ class: 'assistant-scribe', level: 40 }],
    baseXp: 1000, xpMult: 1.1,
    unlocks: { 1: ['unwavered-spell'], 10: ['repent-evil'], 100: ['holier-than-thou'] },
    gains: [
      { everyN: 4, add: { pie: 2, fai: 2 } },
      { everyN: 5, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 6, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 7, add: { sol: 1, pie: 1, fai: 1 } },
    ],
  },
  duelist: {
    name: 'Duelist', tier: 1.5, core: ['str', 'dex'],
    parents: ['fighter'], unlock: [{ class: 'fighter', level: 50 }],
    baseXp: 1500, xpMult: 1.15,
    gains: [
      { everyN: 3, add: { str: 2, dex: 2 } },
      { everyN: 4, add: { dex: 1, end: 1, str: 1, agi: 1 } },
      { everyN: 5, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 6, add: { sol: 1, str: 1, dex: 1 } },
    ],
  },
  ranger: {
    name: 'Ranger', tier: 1.5, core: ['dex', 'agi'],
    parents: ['rogue'], unlock: [{ class: 'rogue', level: 50 }],
    baseXp: 1500, xpMult: 1.15,
    gains: [
      { everyN: 3, add: { dex: 2, agi: 2 } },
      { everyN: 4, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 5, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 6, add: { sol: 1, dex: 1, agi: 1 } },
    ],
  },
  knight: {
    name: 'Knight', tier: 1.5, core: ['dex', 'str', 'end'],
    parents: ['fighter', 'mercenary'],
    unlock: [{ class: 'fighter', level: 50 }, { class: 'mercenary', level: 50 }],
    baseXp: 1500, xpMult: 1.15,
    gains: [
      { everyN: 3, add: { dex: 2, end: 2, str: 2 } },
      { everyN: 4, add: { str: 1, end: 1, dex: 1, agi: 1, sol: 1 } },
      { everyN: 5, add: { int: 1, wis: 1, pie: 1, fai: 1 } },
      { everyN: 6, add: { sol: 1, dex: 1, end: 1, str: 1 } },
    ],
  },
  druid: {
    name: 'Druid', tier: 1.5, core: ['fai', 'dex', 'agi'],
    parents: ['rogue', 'deacon'],
    unlock: [{ class: 'rogue', level: 50 }, { class: 'deacon', level: 50 }],
    baseXp: 1500, xpMult: 1.15,
    gains: [
      { everyN: 3, add: { fai: 2, dex: 2, agi: 2 } },
      { everyN: 4, add: { sol: 1, pie: 1, fai: 1, dex: 1, agi: 1 } },
      { everyN: 5, add: { str: 1, end: 1, int: 1, wis: 1 } },
      { everyN: 6, add: { sol: 1, fai: 1, dex: 1, agi: 1 } },
    ],
  },
  scholar: {
    name: 'Scholar', tier: 1.5, core: ['int', 'wis'],
    parents: ['mage'], unlock: [{ class: 'mage', level: 50 }],
    baseXp: 1500, xpMult: 1.15,
    gains: [
      { everyN: 3, add: { int: 2, wis: 2 } },
      { everyN: 4, add: { fai: 1, pie: 1, int: 1, wis: 1 } },
      { everyN: 5, add: { dex: 1, agi: 1, str: 1, end: 1 } },
      { everyN: 6, add: { sol: 1, int: 1, wis: 1 } },
    ],
  },
};

// ---- upgrades ----
const UPGRADES = {
  'str-hp':       { stat: 'str', cost: 100,  kind: 'hp',        amt: 10,  label: '+10 Health' },
  'str-hpreg':    { stat: 'str', cost: 1000, kind: 'hpRegen',   amt: 0.1, label: '+0.1 Health regen/s' },
  'str-dmg':      { stat: 'str', cost: 100,  kind: 'dmg', tag: 'str', amt: 1, label: '+1 Strength ability damage' },
  'end-hp':       { stat: 'end', cost: 100,  kind: 'hp',        amt: 10,  label: '+10 Health' },
  'end-hpreg':    { stat: 'end', cost: 1000, kind: 'hpRegen',   amt: 0.1, label: '+0.1 Health regen/s' },
  'end-dmg':      { stat: 'end', cost: 100,  kind: 'dmg', tag: 'end', amt: 1, label: '+1 Endurance ability damage' },
  'dex-stam':     { stat: 'dex', cost: 100,  kind: 'stam',      amt: 1,   label: '+1 Stamina' },
  'dex-stamreg':  { stat: 'dex', cost: 1000, kind: 'stamRegen', amt: 0.01, label: '+0.01 Stamina regen/s' },
  'dex-dmg':      { stat: 'dex', cost: 100,  kind: 'dmg', tag: 'dex', amt: 1, label: '+1 Dexterity ability damage' },
  'agi-stam':     { stat: 'agi', cost: 100,  kind: 'stam',      amt: 10,  label: '+10 Stamina' },
  'agi-stamreg':  { stat: 'agi', cost: 1000, kind: 'stamRegen', amt: 0.01, label: '+0.01 Stamina regen/s' },
  'agi-dmg':      { stat: 'agi', cost: 100,  kind: 'dmg', tag: 'agi', amt: 1, label: '+1 Agility ability damage' },
  'int-mana':     { stat: 'int', cost: 100,  kind: 'mana',      amt: 10,  label: '+10 Mana' },
  'int-manareg':  { stat: 'int', cost: 1000, kind: 'manaRegen', amt: 0.01, label: '+0.01 Mana regen/s' },
  'int-dmg':      { stat: 'int', cost: 100,  kind: 'dmg', tag: 'int', amt: 1, label: '+1 Intelligence ability damage' },
  'wis-mana':     { stat: 'wis', cost: 100,  kind: 'mana',      amt: 10,  label: '+10 Mana' },
  'wis-manareg':  { stat: 'wis', cost: 1000, kind: 'manaRegen', amt: 0.01, label: '+0.01 Mana regen/s' },
  'wis-dmg':      { stat: 'wis', cost: 100,  kind: 'dmg', tag: 'wis', amt: 1, label: '+1 Wisdom ability damage' },
  'fai-reson':    { stat: 'fai', cost: 100,  kind: 'reson',     amt: 10,  label: '+10 Resonance' },
  'fai-resonreg': { stat: 'fai', cost: 1000, kind: 'resonRegen', amt: 0.01, label: '+0.01 Resonance regen/s' },
  'fai-dmg':      { stat: 'fai', cost: 100,  kind: 'dmg', tag: 'fai', amt: 1, label: '+1 Faith ability damage' },
  'pie-reson':    { stat: 'pie', cost: 100,  kind: 'reson',     amt: 10,  label: '+10 Resonance' },
  'pie-resonreg': { stat: 'pie', cost: 1000, kind: 'resonRegen', amt: 0.01, label: '+0.01 Piety regen/s' },
  'pie-dmg':      { stat: 'pie', cost: 100,  kind: 'dmg', tag: 'pie', amt: 1, label: '+1 Piety ability damage' },
};
const UPGRADE_STATS = ['str', 'end', 'dex', 'agi', 'int', 'wis', 'fai', 'pie'];

// ---- Books ----
const T05_IDS = ['squire-trainee', 'scouts-runner', 'mages-apprentice', 'assistant-scribe'];
const T1_IDS = ['fighter', 'rogue', 'mercenary', 'monk', 'mage', 'deacon'];
const T15_IDS = ['duelist', 'ranger', 'knight', 'druid', 'scholar'];

// Book 1 (chapter.killXp = per-victory XP; gearLvl = chapter; gold = chapter×10)
const BOOK1 = [
  { name: 'Training Ground', reward: { classless: 2500 }, killXp: 50, gold: 10, gearLvl: 1, pages: [
    { id: 'dummy1', name: 'Training Dummy', hp: 25, stats: { end: 8 }, noRegen: true, noShield: true,
      abilities: ['stare-menacingly'] },
    { id: 'dummy2', name: 'Bigger Training Dummy', hp: 100, stats: { end: 12 },
      abilities: ['intimidating-demeanor', 'being-bigger', 'buckle'] },
    { id: 'dummy3', name: 'Rotating Dummy', hp: 50, stats: { str: 10, end: 8 },
      abilities: ['left-fist', 'right-fist'] },
  ]},
  { name: 'Learning the Basics', reward: { classless: 4000, t05: 4000 }, killXp: 80, gold: 20, gearLvl: 2, pages: [
    { id: 'billy', name: 'Trainee Billy (8)', hp: 150, stats: { str: 15, end: 10, dex: 8 },
      abilities: ['weak-swing', 'drop-shield', 'cower'] },
    { id: 'billys-mom', name: "Billy's Mom (32)", hp: 250, stats: { str: 20, wis: 10, end: 12 },
      abilities: ['vengeful-strike', 'you-monster', 'skull-crack'] },
    { id: 'james', name: 'Retiree James (108)', hp: 185, stats: { dex: 10, agi: 10, wis: 10 },
      abilities: ['back-in-my-day', 'where-am-i', 'shuffle', 'cane-swipe'] },
  ]},
  { name: 'Adventure Guild Entrance Practical', reward: { classless: 9000, t05: 9000 }, killXp: 180, gold: 30, gearLvl: 3, pages: [
    { id: 'florance', name: 'Rankless Adventurer Florance', hp: 350, stats: { dex: 16, agi: 12, end: 10 },
      abilities: ['twin-strike', 'throwing-dagger', 'leg-sweep'] },
    { id: 'amanda', name: 'Rankless Adventurer Amanda', hp: 320, stats: { agi: 16, dex: 12, wis: 10 },
      abilities: ['viper-strike', 'poison-dagger', 'distract'] },
    { id: 'martin', name: 'Low Copper Rank Martin', hp: 450, stats: { str: 18, int: 16, end: 12 },
      abilities: ['whirlwind-slash', 'icicle-darts', 'counter-strike', 'glacial-fist'] },
  ]},
  { name: 'First Quest: Clean out the Sewer', reward: { classless: 16000, t05: 16000 }, killXp: 320, gold: 40, gearLvl: 4, pages: [
    { id: 'baby-rat', name: 'Baby Rat (Awww)', hp: 120, stats: { agi: 14, wis: 8 },
      allies: ['baby-rat'],
      abilities: ['skittish', 'be-adorable', 'knaw', 'flee'] },
    { id: 'feeble-slime', name: 'Feeble Slime', hp: 220, stats: { end: 14, agi: 12 },
      allies: ['feeble-slime'],
      abilities: ['jump-attack', 'vibrate', 'cower'] },
    { id: 'diseased-rat', name: 'Diseased Rat', hp: 400, stats: { end: 20, str: 12 },
      allies: ['diseased-rat'],
      abilities: ['diseased', 'projectile-bile', 'gnash-teeth', 'putrid-smell'] },
  ]},
  { name: 'Explore Just Outside the Outpost Gate', reward: { classless: 30000, t05: 30000 }, killXp: 600, gold: 50, gearLvl: 5, pages: [
    { id: 'slime', name: 'Slime', hp: 520, stats: { agi: 22, end: 16 },
      allies: ['slime'],
      abilities: ['jump-attack', 'rebound', 'gunk-shot', 'serpentine'] },
    { id: 'horned-rabbit', name: 'Horned Rabbit', hp: 560, stats: { dex: 20, end: 20, agi: 16 },
      allies: ['horned-rabbit'],
      abilities: ['war-cry-smol', 'headbutt', 'flee'] },
    { id: 'angry-mole', name: 'Angry Mole (You Stepped On His Home)', hp: 680, stats: { str: 24, dex: 20, end: 16 },
      abilities: ['fury', 'claw-swipes', 'rock-throw'] },
  ]},
  { name: 'First Goblin, How Hard Could It Be?', reward: { classless: 50000, t05: 50000, t1: 50000 }, killXp: 1200, gold: 60, gearLvl: 6, boss: true, pages: [
    { id: 'goblin', name: 'Wandering Goblin', hp: 1400, stats: { str: 30, wis: 12, end: 20, agi: 18 },
      abilities: ['knee-in-groin', 'bonk-on-head', 'wack', 'thwack', 'crack', 'whats-uhh'] },
  ]},
];

// Book 2 (gearLvl = 6+chapter; gold = 80+20×chapter)
const BOOK2 = [
  { name: 'Verify Your Kills at the Guild', reward: { classless: 80000, t05: 80000, t1: 80000 }, killXp: 1900, gold: 100, gearLvl: 7, pages: [
    { id: 'town-guard', name: 'Town Guard', hp: 1400, stats: { str: 28, end: 26, wis: 20, pie: 18 },
      abilities: ['halt', 'present-papers', 'back-of-line', 'pay-the-fine', 'disrespect-toll'] },
    { id: 'food-merchant', name: 'Food Stand Merchant', hp: 1600, stats: { int: 26, dex: 24, end: 20, str: 18 },
      abilities: ['deals-to-die-for', 'special-recipe', 'supposed-sharp', 'dont-be-picky', 'one-for-two'] },
    { id: 'pick-pocket', name: 'Pick Pocket', hp: 1300, stats: { str: 24, dex: 26, agi: 26, wis: 18 },
      abilities: ['hand-over-coin', 'swiping-slash', 'guys-broke', 'skidaddle'] },
  ]},
  { name: 'Guild Advancement Practical', reward: { classless: 120000, t05: 120000, t1: 120000 }, killXp: 2700, gold: 120, gearLvl: 8, pages: [
    { id: 'amanda-2', name: 'Low Copper Rank Amanda', hp: 2000, stats: { agi: 32, dex: 28, wis: 22 },
      abilities: ['viper-strike-u', 'poison-daggers-u', 'distract', 'bolas-toss'] },
    { id: 'brigitte', name: 'Low Copper Rank Brigitte', hp: 2200, stats: { dex: 32, agi: 30, end: 22 },
      abilities: ['spear-throw', 'deflecting-stance', 'arterial-strike', 'jab-flurry', 'sonic-assault'] },
    { id: 'martin-2', name: 'Mid Copper Rank Martin', hp: 2600, stats: { str: 32, int: 30, end: 24, wis: 20 },
      abilities: ['whirlwind-slash-b2', 'icicle-darts-u', 'counter-strike', 'glacial-fist-u', 'frost-enchant'] },
  ]},
  { name: 'Deal With the Goblin Menace', reward: { classless: 170000, t05: 170000, t1: 170000 }, killXp: 3600, gold: 140, gearLvl: 9, pages: [
    { id: 'several-slimes', name: 'Several Slimes', hp: 2400, stats: { agi: 34, end: 30, wis: 24 },
      allies: ['several-slimes', 'several-slimes'],
      abilities: ['hum-in-unison', 'multiply', 'gunk-bombardment', 'rebound'] },
    { id: 'rabbit-alpha', name: 'Horned Rabbit Alpha', hp: 3000, stats: { str: 36, end: 32, agi: 28 },
      abilities: ['roar', 'full-bore', 'after-image', 'carotid-crunch'] },
    { id: 'tree-beetle', name: 'Giant Tree Beetle', hp: 3200, stats: { str: 34, end: 36, agi: 26 },
      abilities: ['camouflage', 'mandible-crunch', 'take-flight'] },
    { id: 'timber-wolves', name: 'Timber Wolf', hp: 2600, stats: { str: 32, agi: 34, dex: 28, wis: 22 },
      allies: ['timber-wolves'],
      abilities: ['flanking-strike', 'howl', 'pounce', 'latching-bite'] },
  ]},
  { name: 'Goblin Encampment Found!', reward: { classless: 230000, t05: 230000, t1: 230000 }, killXp: 4600, gold: 160, gearLvl: 10, pages: [
    { id: 'goblin-trapper', name: 'Goblin Trapper', hp: 3400, stats: { dex: 40, agi: 32, end: 28 },
      abilities: ['ambush', 'rope-snag', 'sedation-dart', 'bone-knife'] },
    { id: 'goblin-sharpshooter', name: 'Goblin Sharpshooter', hp: 3200, stats: { dex: 44, agi: 30, end: 26 },
      abilities: ['ambush', 'leg-shot', 'scatter-shot', 'between-eyes'] },
    { id: 'goblin-guards', name: 'Goblin Guard', hp: 3600, stats: { end: 42, dex: 34, str: 30, wis: 22 },
      allies: ['goblin-guards'],
      abilities: ['shield-bash', 'fortified', 'simultaneous-slash', 'panic'] },
    { id: 'hobgoblin', name: 'Enraged Hobgoblin', hp: 5000, stats: { str: 48, end: 40, agi: 28 },
      abilities: ['swing-wildly', 'full-bore', 'war-cry-hob', 'berserk'] },
    { id: 'goblin-elder', name: 'Goblin Elder', hp: 6000, stats: { str: 46, wis: 30, end: 36, agi: 28 },
      abilities: ['knee-in-groin-u', 'bonk-on-head-u', 'wack-u', 'thwack-u', 'crack-u', 'whats-that'] },
  ]},
  { name: 'Better Head Back Before Dark', reward: { classless: 300000, t05: 300000, t1: 300000 }, killXp: 5700, gold: 180, gearLvl: 11, pages: [
    { id: 'fleeing-wolves', name: 'Fleeing Timber Wolf', hp: 3000, stats: { str: 36, agi: 38, wis: 24 },
      allies: ['fleeing-wolves', 'fleeing-wolves'],
      abilities: ['yelp', 'bite', 'bite', 'full-bore', 'skidaddle'] },
    { id: 'silence', name: 'Silence...', hp: 1, req: 1, silence: true, noRegen: true, noShield: true,
      stats: { sol: 50 },
      abilities: ['nothingness', 'too-quiet', 'something-wrong', 'neck-hairs', 'not-supposed'] },
    { id: 'wounded-amanda', name: 'Wounded Adventurer Amanda', hp: 2000, req: 1, reverse: true, noShield: true,
      stats: { agi: 32, dex: 28, wis: 22, sol: 30 },
      abilities: ['have-to-run', 'not-normal', 'slow-it-down', 'just-leave-him'] },
  ]},
  { name: 'Is That You... Martin?', reward: { classless: 380000, t05: 380000, t1: 380000, t15: 380000 }, killXp: 6900, gold: 200, gearLvl: 12, boss: true, pages: [
    { id: 'corrupted-wolf', name: 'Corrupted Timber Wolf', hp: 14000, dormant: true, startFeast: true,
      stats: { str: 55, dex: 48, agi: 46, end: 50, wis: 30, sol: 40 },
      playerAllies: ['amanda-ally'],
      abilities: ['ferocious-howl', 'hatred-brews', 'coagulated-claws', 'relentless-assault', 'decisive-lunge', 'feast'] },
  ]},
];

// ally templates (amanda = half the player's stats, built at runtime)
const ALLY_DEFS = {
  'amanda-ally': { name: 'Amanda', halfPlayer: true,
    abilities: ['viper-strike-u', 'poison-daggers-u', 'distract', 'bolas-toss'] },
};

const BOOKS = [
  { name: 'Book 1', content: BOOK1, mult: 1 },
  { name: 'Book 2', content: BOOK2, mult: 1 },
  { name: 'Book 2 Hard', content: BOOK2, mult: 3 },
  { name: 'Book 2 Nightmare', content: BOOK2, mult: 9 },
  { name: 'Book 2 Hell', content: BOOK2, mult: 27 },
];
const BOOK_PAGES = BOOKS.map((b) => b.content.reduce((a, c) => a + c.pages.length, 0));
const BOOK_STARTS = BOOK_PAGES.reduce((acc, n, i) => { acc.push(i === 0 ? 0 : acc[i - 1] + BOOK_PAGES[i - 1]); return acc; }, []);
const TOTAL_PAGES = BOOK_PAGES.reduce((a, b) => a + b, 0);
